### ISSUE TITLE
Tweaks to New App 

### ISSUE THREAD

**Issue by markmacpherson** [cadets-ca/ets#18]
In reviewing the new version of the app, I have a few recommendations that I think we should take before releasing it to the CTCs:

- [x] Remove personal info from the list of pilots (emails and names from the default entries are real)
- [x] Replace the background image with a different image (no contact info, I think) #13 
- [x] Replace the app icon and app name with a new one (having both apps installed makes it very hard to tell the difference between the two) #13

**Comment by kirvanp** [comment]
1) There aren't supposed to be any real people in the default version of the app, but there does have to be default pilots otherwise it is very cumbersome for Apple's reviewers to create content as they have to create pilots from scratch with the right quals to be able to fly without errors which is hard for non-ACGP people to do. I suggest modifying the default sql database that ships with the app to get rid of the real people. 

2) I will send Hughes the illustrator file for the app icon. If all you want to do is make them distinguishable, you may wish to simply modify the existing icon. I suggest removing the circle around the glider (Apple was recommending that with iOS 7, nobody does that anymore) and changing the background color.

**Comment by markmacpherson** [comment]
@kirvanp yes, I think modifying the existing icon is perfect. Something just slightly different so you can tell which is which if you have both installed.

**Comment by huguesf** [comment]
Change of icon is completed as part of #13.
